default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: exercise_development

test:
  <<: *default
  database: exercise_test

production:
  <<: *default
  database: exercise_production
  username: exercise
  password: <%= ENV['EXERCISE_DATABASE_PASSWORD'] %>
